/*---------------------------------------------------------*/
/*                                                         */
/*   DN Jullia 2024.0 -> Part Of DN Family                 */
/*   Jullia Main Header File                               */
/*   Copyright (c) 2024 by Branislav Juhas                 */
/*                                                         */
/*---------------------------------------------------------*/

#include "envt.h"


int main()
{
    TEnvironment environment;
    environment.run();
    return 0;
}